spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contract?characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
      mode: HTML5
      encoding: UTF-8
      cache: false